# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.define "rockym" do |rocky|
    rocky.vm.box = "eurolinux-vagrant/rocky-8"
    rocky.vm.hostname = "rockylinux8.local"
    rocky.vm.provider :virtualbox
    rocky.vm.disk :disk, size: "75GB", primary: true
    rocky.vm.network "private_network", ip: "192.168.56.200"

    config.vm.provider "virtualbox" do |rvb|
      rvb.memory = "4096"
      rvb.cpus = 1
    end
  end
end
