# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.define "ubuntum" do |ubuntu|
    ubuntu.vm.box = "ubuntu/focal64"
    ubuntu.vm.hostname = "ubuntu22.local"
    ubuntu.vm.provider :virtualbox
    ubuntu.vm.disk :disk, size: "75GB", primary: true
    ubuntu.vm.network "private_network", ip: "192.168.56.100"

    config.vm.provider "virtualbox" do |uvb|
      uvb.memory = "4096"
      uvb.cpus = 2
    end
  end

end
